---
- name: Check connection between endpoints
  hosts: cpe2
  gather_facts: false
  tasks:
    - name: Ping from CPE2
      ios_ping:
        dest: "{{ item }}"
        vrf: vrf1a
        count: 5
        source: 192.168.151.1
      loop:
        - 192.168.151.2
        - 192.168.151.3

