- name: Create VRF (virtual router) and associate it with a VNI
  nxos_vrf:
    rd: auto
    vni: "{{ vrf_vni }}"
    state: "{{ global_state }}"
    name: "{{ vrf_name }}"
  when: tenant is defined
    
- name: Address family specific settings for the VRF VNI (IPv4)
  nxos_vrf_af:
    state: "{{ global_state }}"
    afi: ipv4
    route_target_both_auto_evpn: yes
    vrf: "{{ vrf_name }}"
  when: tenant is defined
        
- name: Address family specific settings for the VRF VNI (IPv6)
  nxos_vrf_af:
    state: "{{ global_state }}"
    afi: ipv6
    route_target_both_auto_evpn: yes
    vrf: "{{ vrf_name }}"
  when: tenant is defined
