---
- name: bind VNI and VTEP
  nxos_vxlan_vtep_vni:
    interface: nve1
    vni: '{{ item.vni }}'
    multicast_group: '{{ item.multicast_group }}'
    state: '{{ global_state }}'
  when: tenant is defined
  with_items:
    - "{{ networks }}"